name: Testing

on: [ push, pull_request ]

env:
  URI: ${{ secrets.URI }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: npm run install-server
      - run: npm run test
